// Scored lexicon with language, part-of-speech, lemma, and sentiment score (-5..5).
// Lightweight and local-only; no network calls required.
const LEXICON = [
    {sentiment: 'positive', lang: 'en', pos: 'adj', word: 'good', lemma: 'good', score: 2},
    {sentiment: 'positive', lang: 'en', pos: 'adj', word: 'excellent', lemma: 'excellent', score: 4},
    {sentiment: 'positive', lang: 'en', pos: 'adj', word: 'awesome', lemma: 'awesome', score: 4},
    {sentiment: 'positive', lang: 'en', pos: 'adj', word: 'amazing', lemma: 'amazing', score: 4},
    {sentiment: 'positive', lang: 'en', pos: 'adj', word: 'great', lemma: 'great', score: 3},
    {sentiment: 'positive', lang: 'en', pos: 'adj', word: 'fantastic', lemma: 'fantastic', score: 4},
    {sentiment: 'positive', lang: 'en', pos: 'adj', word: 'impressive', lemma: 'impressive', score: 3},
    {sentiment: 'positive', lang: 'en', pos: 'adj', word: 'positive', lemma: 'positive', score: 2},
    {sentiment: 'positive', lang: 'en', pos: 'adj', word: 'satisfied', lemma: 'satisfied', score: 3},
    {sentiment: 'positive', lang: 'en', pos: 'adj', word: 'successful', lemma: 'successful', score: 3},
    {sentiment: 'positive', lang: 'en', pos: 'adj', word: 'effective', lemma: 'effective', score: 3},
    {sentiment: 'positive', lang: 'en', pos: 'adj', word: 'useful', lemma: 'useful', score: 2},
    {sentiment: 'positive', lang: 'en', pos: 'adj', word: 'beautiful', lemma: 'beautiful', score: 3},
    {sentiment: 'positive', lang: 'en', pos: 'adj', word: 'happy', lemma: 'happy', score: 3},
    {sentiment: 'positive', lang: 'en', pos: 'adj', word: 'delighted', lemma: 'delighted', score: 4},
    {sentiment: 'positive', lang: 'en', pos: 'adj', word: 'optimistic', lemma: 'optimistic', score: 3},
    {sentiment: 'positive', lang: 'en', pos: 'adj', word: 'creative', lemma: 'creative', score: 2},
    {sentiment: 'positive', lang: 'en', pos: 'adj', word: 'outstanding', lemma: 'outstanding', score: 4},
    {sentiment: 'positive', lang: 'en', pos: 'adj', word: 'reliable', lemma: 'reliable', score: 3},
    {sentiment: 'positive', lang: 'en', pos: 'adj', word: 'perfect', lemma: 'perfect', score: 5},
    {sentiment: 'positive', lang: 'en', pos: 'adj', word: 'valuable', lemma: 'valuable', score: 3},
    {sentiment: 'positive', lang: 'en', pos: 'adj', word: 'superb', lemma: 'superb', score: 4},
    {sentiment: 'positive', lang: 'en', pos: 'adj', word: 'recommended', lemma: 'recommended', score: 3},
    {sentiment: 'positive', lang: 'en', pos: 'verb', word: 'appreciate', lemma: 'appreciate', score: 3},
    {sentiment: 'positive', lang: 'en', pos: 'verb', word: 'admire', lemma: 'admire', score: 3},
    {sentiment: 'positive', lang: 'en', pos: 'verb', word: 'support', lemma: 'support', score: 2},
    {sentiment: 'positive', lang: 'en', pos: 'verb', word: 'love', lemma: 'love', score: 5},
    {sentiment: 'positive', lang: 'en', pos: 'verb', word: 'enjoy', lemma: 'enjoy', score: 3},
    {sentiment: 'positive', lang: 'en', pos: 'verb', word: 'like', lemma: 'like', score: 2},
    {sentiment: 'positive', lang: 'en', pos: 'verb', word: 'trust', lemma: 'trust', score: 3},
    {sentiment: 'positive', lang: 'en', pos: 'verb', word: 'recommend', lemma: 'recommend', score: 3},
    {sentiment: 'positive', lang: 'en', pos: 'verb', word: 'praise', lemma: 'praise', score: 3},
    {sentiment: 'positive', lang: 'en', pos: 'verb', word: 'value', lemma: 'value', score: 3},
    {sentiment: 'positive', lang: 'en', pos: 'verb', word: 'prefer', lemma: 'prefer', score: 2},
    {sentiment: 'positive', lang: 'en', pos: 'verb', word: 'celebrate', lemma: 'celebrate', score: 3},
    {sentiment: 'positive', lang: 'en', pos: 'verb', word: 'approve', lemma: 'approve', score: 2},
    {sentiment: 'positive', lang: 'en', pos: 'verb', word: 'encourage', lemma: 'encourage', score: 3},
    {sentiment: 'positive', lang: 'en', pos: 'verb', word: 'respect', lemma: 'respect', score: 3},
    {sentiment: 'positive', lang: 'en', pos: 'verb', word: 'embrace', lemma: 'embrace', score: 3},
    {sentiment: 'positive', lang: 'en', pos: 'verb', word: 'benefit', lemma: 'benefit', score: 2},
    {sentiment: 'positive', lang: 'en', pos: 'verb', word: 'succeed', lemma: 'succeed', score: 3},
    {sentiment: 'positive', lang: 'en', pos: 'verb', word: 'improve', lemma: 'improve', score: 3},
    {sentiment: 'positive', lang: 'en', pos: 'verb', word: 'enhance', lemma: 'enhance', score: 3},
    {sentiment: 'positive', lang: 'en', pos: 'phrase', word: 'highly recommended', lemma: 'highly recommended', score: 4},
    {sentiment: 'positive', lang: 'en', pos: 'phrase', word: 'very good experience', lemma: 'very good experience', score: 3},
    {sentiment: 'positive', lang: 'en', pos: 'phrase', word: 'exceeded expectations', lemma: 'exceeded expectations', score: 4},
    {sentiment: 'positive', lang: 'en', pos: 'phrase', word: 'great improvement', lemma: 'great improvement', score: 3},
    {sentiment: 'positive', lang: 'en', pos: 'phrase', word: 'works perfectly', lemma: 'works perfectly', score: 4},
    {sentiment: 'positive', lang: 'en', pos: 'phrase', word: 'worth it', lemma: 'worth it', score: 2},
    {sentiment: 'positive', lang: 'gr', pos: 'adj', word: 'καλός', lemma: 'καλός', score: 2},
    {sentiment: 'positive', lang: 'gr', pos: 'adj', word: 'καλή', lemma: 'καλός', score: 2},
    {sentiment: 'positive', lang: 'gr', pos: 'adj', word: 'καλό', lemma: 'καλός', score: 2},
    {sentiment: 'positive', lang: 'gr', pos: 'adj', word: 'υπέροχος', lemma: 'υπέροχος', score: 4},
    {sentiment: 'positive', lang: 'gr', pos: 'adj', word: 'εξαιρετικός', lemma: 'εξαιρετικός', score: 4},
    {sentiment: 'positive', lang: 'gr', pos: 'adj', word: 'τέλειος', lemma: 'τέλειος', score: 5},
    {sentiment: 'positive', lang: 'gr', pos: 'adj', word: 'καταπληκτικός', lemma: 'καταπληκτικός', score: 4},
    {sentiment: 'positive', lang: 'gr', pos: 'adj', word: 'θετικός', lemma: 'θετικός', score: 2},
    {sentiment: 'positive', lang: 'gr', pos: 'adj', word: 'εντυπωσιακός', lemma: 'εντυπωσιακός', score: 3},
    {sentiment: 'positive', lang: 'gr', pos: 'adj', word: 'ευχάριστος', lemma: 'ευχάριστος', score: 3},
    {sentiment: 'positive', lang: 'gr', pos: 'adj', word: 'ικανοποιημένος', lemma: 'ικανοποιημένος', score: 3},
    {sentiment: 'positive', lang: 'gr', pos: 'adj', word: 'επιτυχημένος', lemma: 'επιτυχημένος', score: 3},
    {sentiment: 'positive', lang: 'gr', pos: 'adj', word: 'αποτελεσματικός', lemma: 'αποτελεσματικός', score: 3},
    {sentiment: 'positive', lang: 'gr', pos: 'adj', word: 'χρήσιμος', lemma: 'χρήσιμος', score: 2},
    {sentiment: 'positive', lang: 'gr', pos: 'adj', word: 'όμορφος', lemma: 'όμορφος', score: 3},
    {sentiment: 'positive', lang: 'gr', pos: 'adj', word: 'χαρούμενος', lemma: 'χαρούμενος', score: 3},
    {sentiment: 'positive', lang: 'gr', pos: 'adj', word: 'ευτυχισμένος', lemma: 'ευτυχισμένος', score: 4},
    {sentiment: 'positive', lang: 'gr', pos: 'adj', word: 'αισιόδοξος', lemma: 'αισιόδοξος', score: 3},
    {sentiment: 'positive', lang: 'gr', pos: 'adj', word: 'δημιουργικός', lemma: 'δημιουργικός', score: 2},
    {sentiment: 'positive', lang: 'gr', pos: 'adj', word: 'αξιόπιστος', lemma: 'αξιόπιστος', score: 3},
    {sentiment: 'positive', lang: 'gr', pos: 'adj', word: 'φανταστικός', lemma: 'φανταστικός', score: 4},
    {sentiment: 'positive', lang: 'gr', pos: 'verb', word: 'εκτιμώ', lemma: 'εκτιμώ', score: 4},
    {sentiment: 'positive', lang: 'gr', pos: 'verb', word: 'θαυμάζω', lemma: 'θαυμάζω', score: 5},
    {sentiment: 'positive', lang: 'gr', pos: 'verb', word: 'υποστηρίζω', lemma: 'υποστηρίζω', score: 2},
    {sentiment: 'positive', lang: 'gr', pos: 'verb', word: 'αγαπώ', lemma: 'αγαπώ', score: 5},
    {sentiment: 'positive', lang: 'gr', pos: 'verb', word: 'απολαμβάνω', lemma: 'απολαμβάνω', score: 3},
    {sentiment: 'positive', lang: 'gr', pos: 'verb', word: 'μου αρέσει', lemma: 'μου αρέσει', score: 3},
    {sentiment: 'positive', lang: 'gr', pos: 'verb', word: 'εμπιστεύομαι', lemma: 'εμπιστεύομαι', score: 3},
    {sentiment: 'positive', lang: 'gr', pos: 'verb', word: 'προτείνω', lemma: 'προτείνω', score: 3},
    {sentiment: 'positive', lang: 'gr', pos: 'verb', word: 'επαινώ', lemma: 'επαινώ', score: 3},
    {sentiment: 'positive', lang: 'gr', pos: 'verb', word: 'εκθειάζω', lemma: 'εκθειάζω', score: 4},
    {sentiment: 'positive', lang: 'gr', pos: 'verb', word: 'σέβομαι', lemma: 'σέβομαι', score: 3},
    {sentiment: 'positive', lang: 'gr', pos: 'verb', word: 'ενθαρρύνω', lemma: 'ενθαρρύνω', score: 3},
    {sentiment: 'positive', lang: 'gr', pos: 'verb', word: 'εγκρίνω', lemma: 'εγκρίνω', score: 2},
    {sentiment: 'positive', lang: 'gr', pos: 'verb', word: 'προτιμώ', lemma: 'προτιμώ', score: 2},
    {sentiment: 'positive', lang: 'gr', pos: 'verb', word: 'πανηγυρίζω', lemma: 'πανηγυρίζω', score: 3},
    {sentiment: 'positive', lang: 'gr', pos: 'verb', word: 'βελτιώνω', lemma: 'βελτιώνω', score: 3},
    {sentiment: 'positive', lang: 'gr', pos: 'verb', word: 'ενισχύω', lemma: 'ενισχύω', score: 3},
    {sentiment: 'positive', lang: 'gr', pos: 'verb', word: 'πετυχαίνω', lemma: 'πετυχαίνω', score: 3},
    {sentiment: 'positive', lang: 'gr', pos: 'verb', word: 'ωφελώ', lemma: 'ωφελώ', score: 3},
    {sentiment: 'positive', lang: 'gr', pos: 'verb', word: 'κερδίζω', lemma: 'κερδίζω', score: 3},
    {sentiment: 'positive', lang: 'gr', pos: 'phrase', word: 'πολύ καλό αποτέλεσμα', lemma: 'πολύ καλό αποτέλεσμα', score: 3},
    {sentiment: 'positive', lang: 'gr', pos: 'phrase', word: 'με ικανοποίησε', lemma: 'με ικανοποίησε', score: 3},
    {sentiment: 'positive', lang: 'gr', pos: 'phrase', word: 'άψογη εμπειρία', lemma: 'άψογη εμπειρία', score: 4},
    {sentiment: 'positive', lang: 'gr', pos: 'phrase', word: 'το συνιστώ ανεπιφύλακτα', lemma: 'το συνιστώ ανεπιφύλακτα', score: 4},
    {sentiment: 'positive', lang: 'gr', pos: 'phrase', word: 'μεγάλη βελτίωση', lemma: 'μεγάλη βελτίωση', score: 3},
    {sentiment: 'positive', lang: 'gr', pos: 'phrase', word: 'πέτυχε τον στόχο', lemma: 'πέτυχε τον στόχο', score: 3},
    {sentiment: 'negative', lang: 'en', pos: 'adj', word: 'bad', lemma: 'bad', score: -2},
    {sentiment: 'negative', lang: 'en', pos: 'adj', word: 'awful', lemma: 'awful', score: -4},
    {sentiment: 'negative', lang: 'en', pos: 'adj', word: 'terrible', lemma: 'terrible', score: -4},
    {sentiment: 'negative', lang: 'en', pos: 'adj', word: 'horrible', lemma: 'horrible', score: -4},
    {sentiment: 'negative', lang: 'en', pos: 'adj', word: 'negative', lemma: 'negative', score: -2},
    {sentiment: 'negative', lang: 'en', pos: 'adj', word: 'disappointing', lemma: 'disappointing', score: -3},
    {sentiment: 'negative', lang: 'en', pos: 'adj', word: 'weak', lemma: 'weak', score: -2},
    {sentiment: 'negative', lang: 'en', pos: 'adj', word: 'problematic', lemma: 'problematic', score: -3},
    {sentiment: 'negative', lang: 'en', pos: 'adj', word: 'useless', lemma: 'useless', score: -4},
    {sentiment: 'negative', lang: 'en', pos: 'adj', word: 'wrong', lemma: 'wrong', score: -2},
    {sentiment: 'negative', lang: 'en', pos: 'adj', word: 'dangerous', lemma: 'dangerous', score: -4},
    {sentiment: 'negative', lang: 'en', pos: 'adj', word: 'insufficient', lemma: 'insufficient', score: -2},
    {sentiment: 'negative', lang: 'en', pos: 'adj', word: 'failed', lemma: 'failed', score: -3},
    {sentiment: 'negative', lang: 'en', pos: 'adj', word: 'ugly', lemma: 'ugly', score: -3},
    {sentiment: 'negative', lang: 'en', pos: 'adj', word: 'boring', lemma: 'boring', score: -2},
    {sentiment: 'negative', lang: 'en', pos: 'adj', word: 'annoying', lemma: 'annoying', score: -2},
    {sentiment: 'negative', lang: 'en', pos: 'adj', word: 'unacceptable', lemma: 'unacceptable', score: -4},
    {sentiment: 'negative', lang: 'en', pos: 'adj', word: 'disastrous', lemma: 'disastrous', score: -5},
    {sentiment: 'negative', lang: 'en', pos: 'adj', word: 'poor', lemma: 'poor', score: -2},
    {sentiment: 'negative', lang: 'en', pos: 'adj', word: 'defective', lemma: 'defective', score: -3},
    {sentiment: 'negative', lang: 'en', pos: 'adj', word: 'trash', lemma: 'trash', score: -4},
    {sentiment: 'negative', lang: 'en', pos: 'verb', word: 'dislike', lemma: 'dislike', score: -2},
    {sentiment: 'negative', lang: 'en', pos: 'verb', word: 'despise', lemma: 'despise', score: -5},
    {sentiment: 'negative', lang: 'en', pos: 'verb', word: 'hate', lemma: 'hate', score: -5},
    {sentiment: 'negative', lang: 'en', pos: 'verb', word: 'reject', lemma: 'reject', score: -3},
    {sentiment: 'negative', lang: 'en', pos: 'verb', word: 'blame', lemma: 'blame', score: -2},
    {sentiment: 'negative', lang: 'en', pos: 'verb', word: 'discourage', lemma: 'discourage', score: -2},
    {sentiment: 'negative', lang: 'en', pos: 'verb', word: 'disappoint', lemma: 'disappoint', score: -3},
    {sentiment: 'negative', lang: 'en', pos: 'verb', word: 'fail', lemma: 'fail', score: -3},
    {sentiment: 'negative', lang: 'en', pos: 'verb', word: 'criticize', lemma: 'criticize', score: -2},
    {sentiment: 'negative', lang: 'en', pos: 'verb', word: 'complain', lemma: 'complain', score: -2},
    {sentiment: 'negative', lang: 'en', pos: 'verb', word: 'doubt', lemma: 'doubt', score: -1},
    {sentiment: 'negative', lang: 'en', pos: 'verb', word: 'mistrust', lemma: 'mistrust', score: -3},
    {sentiment: 'negative', lang: 'en', pos: 'verb', word: 'ignore', lemma: 'ignore', score: -2},
    {sentiment: 'negative', lang: 'en', pos: 'verb', word: 'avoid', lemma: 'avoid', score: -1},
    {sentiment: 'negative', lang: 'en', pos: 'verb', word: 'ruin', lemma: 'ruin', score: -4},
    {sentiment: 'negative', lang: 'en', pos: 'verb', word: 'damage', lemma: 'damage', score: -3},
    {sentiment: 'negative', lang: 'en', pos: 'verb', word: 'worsen', lemma: 'worsen', score: -3},
    {sentiment: 'negative', lang: 'en', pos: 'verb', word: 'suffer', lemma: 'suffer', score: -3},
    {sentiment: 'negative', lang: 'en', pos: 'verb', word: 'attack', lemma: 'attack', score: -3},
    {sentiment: 'negative', lang: 'en', pos: 'verb', word: 'mock', lemma: 'mock', score: -3},
    {sentiment: 'negative', lang: 'en', pos: 'verb', word: 'insult', lemma: 'insult', score: -4},
    {sentiment: 'negative', lang: 'en', pos: 'verb', word: 'frustrate', lemma: 'frustrate', score: -3},
    {sentiment: 'negative', lang: 'en', pos: 'verb', word: 'annoy', lemma: 'annoy', score: -2},
    {sentiment: 'negative', lang: 'en', pos: 'verb', word: 'offend', lemma: 'offend', score: -3},
    {sentiment: 'negative', lang: 'en', pos: 'verb', word: 'threaten', lemma: 'threaten', score: -4},
    {sentiment: 'negative', lang: 'en', pos: 'verb', word: 'regret', lemma: 'regret', score: -2},
    {sentiment: 'negative', lang: 'en', pos: 'phrase', word: 'not worth it', lemma: 'not worth it', score: -2},
    {sentiment: 'negative', lang: 'en', pos: 'phrase', word: 'very bad experience', lemma: 'very bad experience', score: -4},
    {sentiment: 'negative', lang: 'en', pos: 'phrase', word: "didn't like it", lemma: "didn't like it", score: -2},
    {sentiment: 'negative', lang: 'en', pos: 'phrase', word: 'huge disappointment', lemma: 'huge disappointment', score: -4},
    {sentiment: 'negative', lang: 'en', pos: 'phrase', word: "doesn't work", lemma: "doesn't work", score: -3},
    {sentiment: 'negative', lang: 'en', pos: 'phrase', word: 'waste of time', lemma: 'waste of time', score: -4},
    {sentiment: 'negative', lang: 'en', pos: 'phrase', word: 'poor quality', lemma: 'poor quality', score: -3},
    {sentiment: 'negative', lang: 'gr', pos: 'adj', word: 'κακός', lemma: 'κακός', score: -2},
    {sentiment: 'negative', lang: 'gr', pos: 'adj', word: 'άσχημος', lemma: 'άσχημος', score: -2},
    {sentiment: 'negative', lang: 'gr', pos: 'adj', word: 'αρνητικός', lemma: 'αρνητικός', score: -2},
    {sentiment: 'negative', lang: 'gr', pos: 'adj', word: 'απογοητευτικός', lemma: 'απογοητευτικός', score: -3},
    {sentiment: 'negative', lang: 'gr', pos: 'adj', word: 'ανικανοποίητος', lemma: 'ανικανοποίητος', score: -3},
    {sentiment: 'negative', lang: 'gr', pos: 'adj', word: 'αδύναμος', lemma: 'αδύναμος', score: -2},
    {sentiment: 'negative', lang: 'gr', pos: 'adj', word: 'προβληματικός', lemma: 'προβληματικός', score: -3},
    {sentiment: 'negative', lang: 'gr', pos: 'adj', word: 'άχρηστος', lemma: 'άχρηστος', score: -4},
    {sentiment: 'negative', lang: 'gr', pos: 'adj', word: 'λάθος', lemma: 'λάθος', score: -2},
    {sentiment: 'negative', lang: 'gr', pos: 'adj', word: 'επικίνδυνος', lemma: 'επικίνδυνος', score: -4},
    {sentiment: 'negative', lang: 'gr', pos: 'adj', word: 'ανεπαρκής', lemma: 'ανεπαρκής', score: -2},
    {sentiment: 'negative', lang: 'gr', pos: 'adj', word: 'αποτυχημένος', lemma: 'αποτυχημένος', score: -3},
    {sentiment: 'negative', lang: 'gr', pos: 'adj', word: 'βαρετός', lemma: 'βαρετός', score: -2},
    {sentiment: 'negative', lang: 'gr', pos: 'adj', word: 'εκνευριστικός', lemma: 'εκνευριστικός', score: -3},
    {sentiment: 'negative', lang: 'gr', pos: 'adj', word: 'απαράδεκτος', lemma: 'απαράδεκτος', score: -4},
    {sentiment: 'negative', lang: 'gr', pos: 'adj', word: 'τραγικός', lemma: 'τραγικός', score: -4},
    {sentiment: 'negative', lang: 'gr', pos: 'adj', word: 'χάλια', lemma: 'χάλια', score: -3},
    {sentiment: 'negative', lang: 'gr', pos: 'verb', word: 'δεν μου αρέσει', lemma: 'δεν μου αρέσει', score: -2},
    {sentiment: 'negative', lang: 'gr', pos: 'verb', word: 'μισώ', lemma: 'μισώ', score: -5},
    {sentiment: 'negative', lang: 'gr', pos: 'verb', word: 'περιφρονώ', lemma: 'περιφρονώ', score: -4},
    {sentiment: 'negative', lang: 'gr', pos: 'verb', word: 'απορρίπτω', lemma: 'απορρίπτω', score: -3},
    {sentiment: 'negative', lang: 'gr', pos: 'verb', word: 'κατηγορώ', lemma: 'κατηγορώ', score: -2},
    {sentiment: 'negative', lang: 'gr', pos: 'verb', word: 'αποθαρρύνω', lemma: 'αποθαρρύνω', score: -2},
    {sentiment: 'negative', lang: 'gr', pos: 'verb', word: 'απογοητεύω', lemma: 'απογοητεύω', score: -3},
    {sentiment: 'negative', lang: 'gr', pos: 'verb', word: 'αποτυγχάνω', lemma: 'αποτυγχάνω', score: -3},
    {sentiment: 'negative', lang: 'gr', pos: 'verb', word: 'κριτικάρω', lemma: 'κριτικάρω', score: -2},
    {sentiment: 'negative', lang: 'gr', pos: 'verb', word: 'γκρινιάζω', lemma: 'γκρινιάζω', score: -2},
    {sentiment: 'negative', lang: 'gr', pos: 'verb', word: 'αμφισβητώ', lemma: 'αμφισβητώ', score: -1},
    {sentiment: 'negative', lang: 'gr', pos: 'verb', word: 'αγνοώ', lemma: 'αγνοώ', score: -2},
    {sentiment: 'negative', lang: 'gr', pos: 'verb', word: 'αποφεύγω', lemma: 'αποφεύγω', score: -1},
    {sentiment: 'negative', lang: 'gr', pos: 'verb', word: 'βλάπτω', lemma: 'βλάπτω', score: -3},
    {sentiment: 'negative', lang: 'gr', pos: 'verb', word: 'καταστρέφω', lemma: 'καταστρέφω', score: -4},
    {sentiment: 'negative', lang: 'gr', pos: 'verb', word: 'χειροτερεύω', lemma: 'χειροτερεύω', score: -3},
    {sentiment: 'negative', lang: 'gr', pos: 'verb', word: 'απειλώ', lemma: 'απειλώ', score: -4},
    {sentiment: 'negative', lang: 'gr', pos: 'verb', word: 'προσβάλλω', lemma: 'προσβάλλω', score: -3},
    {sentiment: 'negative', lang: 'gr', pos: 'verb', word: 'εκνευρίζω', lemma: 'εκνευρίζω', score: -3},
    {sentiment: 'negative', lang: 'gr', pos: 'verb', word: 'ενοχλώ', lemma: 'ενοχλώ', score: -2},
    {sentiment: 'negative', lang: 'gr', pos: 'verb', word: 'κοροϊδεύω', lemma: 'κοροϊδεύω', score: -3},
    {sentiment: 'negative', lang: 'gr', pos: 'verb', word: 'ειρωνεύομαι', lemma: 'ειρωνεύομαι', score: -3},
    {sentiment: 'negative', lang: 'gr', pos: 'verb', word: 'μετανιώνω', lemma: 'μετανιώνω', score: -2},
    {sentiment: 'negative', lang: 'gr', pos: 'phrase', word: 'δεν αξίζει', lemma: 'δεν αξίζει', score: -2},
    {sentiment: 'negative', lang: 'gr', pos: 'phrase', word: 'δεν μου άρεσε', lemma: 'δεν μου άρεσε', score: -2},
    {sentiment: 'negative', lang: 'gr', pos: 'phrase', word: 'καθόλου καλό', lemma: 'καθόλου καλό', score: -3},
    {sentiment: 'negative', lang: 'gr', pos: 'phrase', word: 'μεγάλη απογοήτευση', lemma: 'μεγάλη απογοήτευση', score: -4},
    {sentiment: 'negative', lang: 'gr', pos: 'phrase', word: 'χάλια εμπειρία', lemma: 'χάλια εμπειρία', score: -4},
    {sentiment: 'negative', lang: 'gr', pos: 'phrase', word: 'δεν λειτουργεί σωστά', lemma: 'δεν λειτουργεί σωστά', score: -3}
];

module.exports = {LEXICON};
